name: Build and Publish Docker image

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read

env:
  IMAGE_NAME:
    ${{ vars.DOCKERHUB_REPOSITORY || format('{0}/api-inventory', secrets.DOCKERHUB_USERNAME) }}

jobs:
  docker:
    if:
      ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch
      == 'master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=tag

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max
